# Generated by Django 2.1.3 on 2018-11-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_name', models.CharField(max_length=612)),
                ('pl_nickname', models.CharField(max_length=612)),
                ('pl_uri', models.CharField(max_length=612)),
                ('pl_plays', models.IntegerField(default=0)),
            ],
        ),
    ]
