from django.db import models

#Database tables

#Playlist table
#pl_ => playlist
#Note: id field created automatically, primary key
    #Probably a method of the parent class, django.db.models.Model?
class Playlist(models.Model):
    pl_name = models.CharField(max_length = 612)
    pl_nickname = models.CharField(max_length = 612)
    pl_uri = models.CharField(max_length = 612)
    pl_plays = models.IntegerField(default = 0)
    
    def __str__(self):
        return self.pl_name

    def hasBeenPlayed(self):
        return self.pl_plays > 0

# User table - do I need this, or autogenerated by Django?
# class User(models.Model):
#     username = models.CharField(max_length = 64)
#     #salt, etc

